devices:
  - name: "R-Gateway"
    host: "192.168.1.1"
    username: "root"
    password: "cisco"
    device_type: "linux"
    role: "core"
    interface: "eth0"

  - name: "R-Office"
    host: "192.168.1.2"
    username: "root"
    password: "cisco"
    device_type: "linux"
    role: "office"
    interface: "eth0"

  - name: "R-Server"
    host: "192.168.1.3"
    username: "root"
    password: "cisco"
    device_type: "linux"
    role: "server"
    interface: "eth0"

  - name: "R-Attacker"
    host: "192.168.1.4"
    username: "root"
    password: "cisco"
    device_type: "linux"
    role: "attacker"
    interface: "eth0"
